### ISSUE TITLE
Middleware test fails

### ISSUE THREAD

**Issue by matteobucci** [sidhantpanda/docker-express-typescript-boilerplate#16]
Hello, and first of all congratulation on this project!

I was trying to launch some commands and I noticed that when running tests I got a failure.

The code is on 
`__tests/middleware/request-middleware/test.ts`

```
 FAIL  __tests/middleware/request-middleware.test.ts
  ● Error Handling Middleware › Handover request to express error handler on error

    test error

      48 | 
      49 |      test('Handover request to express error handler on error', async () => {
    > 50 |              const err = new Error('test error')
         |                          ^
      51 |              const sampleRoute = async (req?: any, res?: any, nextHandler?: any) => {
      52 |                      throw err
      53 |              }

      at __tests/middleware/request-middleware.test.ts:50:15
      at __tests/middleware/request-middleware.test.ts:8:71
      at Object.<anonymous>.__awaiter (__tests/middleware/request-middleware.test.ts:4:12)
      at Object.<anonymous> (__tests/middleware/request-middleware.test.ts:49:72)```

**Comment by sidhantpanda** [comment]
Hey! Thanks for bringing this up 👍 
Resolved the issues
